version: "3.4"
   
services:
  web:
    build: ./chat_community
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  redis:
    image: redis:5
    ports:
      - "6379:6379"
    user: redis
