# Generated by Django 4.1 on 2022-09-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='online',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
